[api]
port = 54321

[db]
port = 54322

[auth]
site_url = "http://localhost:8888"
additional_redirect_urls = ["http://localhost:8888"]

[auth.email]
enable_signup = true
enable_confirmations = false

[functions.sync-pcs-results]
verify_jwt = false

[functions.sync-pcs-race]
verify_jwt = false

[functions.sync-pcs-photos]
verify_jwt = false
